language: cpp
compiler: gcc

branches:
  only:
    - master
    
matrix:
  include:
    - os: linux
      dist: trusty
      env: CXX_COMPILER=g++-8 C_COMPILER=gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      
  
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qt510base qt510multimedia qt510translations qt510tools ; source /opt/qt510/bin/qt510-env.sh ; export QTHOME=/opt/qt510

  - curl -o cmake.tar.gz -O https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.tar.gz
  - mkdir /opt/cmake
  - tar -xf cmake.tar.gz -C /opt/cmake --strip-components=1
  - rm -f cmake.tar.gz
  - export PATH=/opt/cmake/bin:${PATH}

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_C_COMPILER=${C_COMPILER} ..
  - make

