version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017

clone_folder: c:\projects\dining_philosophers

platform: x64
configuration:
  - Debug
  - Release
  
before_build:
  - echo Running cmake..
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH="C:\Qt\5.11.2\msvc2017_64\lib\cmake\Qt5" -DBUILD_SHARED_LIBS=ON ..
  
build:
  project: c:\projects\dining_philosophers\build\dining_philosophers.sln

