version: 1.0.{build}

branches:
  only:
    - master

clone_folder: c:\projects\dining_philosophers
    
image:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release
  
environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017 Win64"
      QTDIR: "C:\\Qt\\5.11.2\\msvc2017_64\\lib\\cmake\\Qt5"
    
    - GENERATOR: "Visual Studio 14 2015"
      QTDIR: "C:\\Qt\\5.11.2\\msvc2015\\lib\\cmake\\Qt5"
    
matrix:
  exclude:
    - image: Visual Studio 2015
      platform: x64
      GENERATOR: "Visual Studio 15 2017 Win64"
      QTDIR: "C:\\Qt\\5.11.2\\msvc2017_64\\lib\\cmake\\Qt5"
      
    - image: Visual Studio 2015
      platform: x64
      GENERATOR: "Visual Studio 14 2015"
      QTDIR: "C:\\Qt\\5.11.2\\msvc2015\\lib\\cmake\\Qt5"
      
    - image: Visual Studio 2015
      platform: Win32
      GENERATOR: "Visual Studio 15 2017 Win64"
      QTDIR: "C:\\Qt\\5.11.2\\msvc2017_64\\lib\\cmake\\Qt5"
      
    - image: Visual Studio 2017
      platform: x64
      GENERATOR: "Visual Studio 14 2015"
      QTDIR: "C:\\Qt\\5.11.2\\msvc2015\\lib\\cmake\\Qt5"
      
    - image: Visual Studio 2017
      platform: Win32
      GENERATOR: "Visual Studio 14 2015"
      QTDIR: "C:\\Qt\\5.11.2\\msvc2015\\lib\\cmake\\Qt5"
      
    - image: Visual Studio 2017
      platform: Win32
      GENERATOR: "Visual Studio 15 2017"
      QTDIR: "C:\\Qt\\5.11.2\\msvc2015\\lib\\cmake\\Qt5"
  
before_build:
  - cmake "-G%GENERATOR%" -DCMAKE_PREFIX_PATH="%QTDIR%" -DBUILD_SHARED_LIBS=ON -H. -Bbuild
  
build:
  project: build\dining_philosophers.sln

